"""Structured error codes for the electrical CAD agent. FAIL CLOSED, never silent fallback."""
from __future__ import annotations


class CadError(Exception):
    def __init__(self, code: str, message: str, details: dict | None = None):
        super().__init__(f"[{code}] {message}")
        self.code = code
        self.message = message
        self.details = details or {}

    def to_dict(self) -> dict:
        return {"ok": False, "error_code": self.code, "error": self.message, "details": self.details}


# Canonical error codes (spec section 38 + regression additions)
DRAWING_NOT_FOUND = "DRAWING_NOT_FOUND"
DRAWING_REVISION_MISMATCH = "DRAWING_REVISION_MISMATCH"
DRAWING_IDENTITY_MISMATCH = "DRAWING_IDENTITY_MISMATCH"
UNKNOWN_UNITS = "UNKNOWN_UNITS"
ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
ENTITY_TYPE_MISMATCH = "ENTITY_TYPE_MISMATCH"
LAYER_NOT_ALLOWED = "LAYER_NOT_ALLOWED"
OUT_OF_SCOPE = "OUT_OF_SCOPE"
SCOPE_VIOLATION = "SCOPE_VIOLATION"
WALL_NOT_FOUND = "WALL_NOT_FOUND"
NO_FREE_WALL_SPACE = "NO_FREE_WALL_SPACE"
COLLISION_DETECTED = "COLLISION_DETECTED"
TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"
TEMPLATE_INTEGRITY_FAIL = "TEMPLATE_INTEGRITY_FAIL"
PANEL_ORIENTATION_FAIL = "PANEL_ORIENTATION_FAIL"
READBACK_FAIL = "READBACK_FAIL"
NETWORK_DISCONNECTED = "NETWORK_DISCONNECTED"
NETWORK_CYCLE = "NETWORK_CYCLE"
ORPHAN_ENTITY = "ORPHAN_ENTITY"
ORPHAN_CALLOUT = "ORPHAN_CALLOUT"
ORPHAN_ENDPOINT = "ORPHAN_ENDPOINT"
ROOM_SEMANTIC_VIOLATION = "ROOM_SEMANTIC_VIOLATION"
ROUNDTRIP_MISMATCH = "ROUNDTRIP_MISMATCH"
VALIDATION_FAIL = "VALIDATION_FAIL"
BACKEND_UNAVAILABLE = "BACKEND_UNAVAILABLE"
BACKEND_AMBIGUOUS = "BACKEND_AMBIGUOUS"
PLAN_HASH_MISMATCH = "PLAN_HASH_MISMATCH"
DELETE_GUARD = "DELETE_GUARD"
PROTECTED_LAYER = "PROTECTED_LAYER"
